### ISSUE TITLE
add code coverage report into PRs

### ISSUE THREAD

**Issue by alan-barzilay** [bndr/pipreqs#417]
As discussed in PR #415, we should add code coverage reports into PRs as part of the test workflow.

possible implementation with [Code Coverage Report](https://github.com/marketplace/actions/code-coverage-report-action):

```
            - name: Produce the coverage report
              uses: insightsengineering/coverage-action@v2
              with:
		path: coverage.xml
		# Publish the rendered output as a PR comment
		publish: true
		# Create a coverage diff report.
		diff: true
		# Branch to diff against.
		diff-branch: next
		# This is where the coverage reports for the
		# `diff-branch` are stored.
		diff-storage: _xml_coverage_reports
		togglable-report: true
```
